### ISSUE TITLE
[bug] Doesn't work with typography plugin and @tailwindcss/jit

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [jjranalli/nightwind#6] opened 2021-03-18 14:10 UTC
I tried to use nightwind with `@tailwindcss/jit` the `@tailwindcss/typography` plugin, but the colors of the heading elements of prosed content didn't got converted. This was only at elements with prose, other elements without the typography plugin were working. When I tried using normal `tailwindcss` instead of `jit`, then all worked fine.

**Comment by jjranalli** [comment] 2021-03-18 14:23
Thanks for pointing this out! I was able to reproduce the issue. Moreover, it doesn't seem to be restricted just to typography, but also to variant classes written using the short syntax, such as `hover:text-blue-600`.

I'll look into it, but chances are this behaviour results from an issue on jit. Nonetheless, any advice or additional feedback on the issue is appreciated

**Comment by HAUDRAUFHAUN** [comment] 2021-03-18 18:09
Thank you for the answer 🙂.

**Comment by jjranalli** [comment] 2021-03-27 18:46
I was able to fix the bug with typography in the new 1.1.7 release, so I'm closing the issue. 

However, I'm still scratching my head about @apply variant classes such as `@apply hover:text-blue-600`. Will be opening a separate issue for that.

**Closed by jjranalli** 2021-03-27 18:46 UTC

**Comment by HAUDRAUFHAUN** [comment] 2021-03-27 18:51
Ok thank you very much 🙏
